# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageAlignment.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1020)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_button = QtWidgets.QPushButton(self.centralwidget)
        self.input_button.setGeometry(QtCore.QRect(20, 40, 91, 31))
        self.input_button.setObjectName("input_button")
        self.quadDetect_button = QtWidgets.QPushButton(self.centralwidget)
        self.quadDetect_button.setGeometry(QtCore.QRect(130, 10, 121, 41))
        self.quadDetect_button.setObjectName("quadDetect_button")
        self.surfaceF_button = QtWidgets.QPushButton(self.centralwidget)
        self.surfaceF_button.setGeometry(QtCore.QRect(130, 60, 121, 41))
        self.surfaceF_button.setObjectName("surfaceF_button")
        self.saveR_button = QtWidgets.QPushButton(self.centralwidget)
        self.saveR_button.setGeometry(QtCore.QRect(460, 10, 101, 41))
        self.saveR_button.setObjectName("saveR_button")
        self.imgEnhance_button = QtWidgets.QPushButton(self.centralwidget)
        self.imgEnhance_button.setGeometry(QtCore.QRect(270, 40, 171, 41))
        self.imgEnhance_button.setObjectName("imgEnhance_button")
        self.srcImg_label = QtWidgets.QLabel(self.centralwidget)
        self.srcImg_label.setGeometry(QtCore.QRect(20, 900, 121, 21))
        self.srcImg_label.setObjectName("srcImg_label")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(1000, 900, 61, 21))
        self.result_label.setObjectName("result_label")
        self.srcImg_View = QtWidgets.QLabel(self.centralwidget)
        self.srcImg_View.setGeometry(QtCore.QRect(20, 120, 900, 760))
        self.srcImg_View.setObjectName("srcImg_View")
        self.result_View = QtWidgets.QLabel(self.centralwidget)
        self.result_View.setGeometry(QtCore.QRect(1000, 120, 900, 760))
        self.result_View.setObjectName("result_View")
        self.note_label = QtWidgets.QLabel(self.centralwidget)
        self.note_label.setGeometry(QtCore.QRect(620, 20, 500, 61))
        self.note_label.setObjectName("note_label")
        self.rotate_Button = QtWidgets.QPushButton(self.centralwidget)
        self.rotate_Button.setGeometry(QtCore.QRect(460, 60, 101, 41))
        self.rotate_Button.setObjectName("rotate_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 22))
        self.menubar.setObjectName("menubar")
        self.menuImage_Alignment = QtWidgets.QMenu(self.menubar)
        self.menuImage_Alignment.setObjectName("menuImage_Alignment")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuImage_Alignment.addSeparator()
        self.menubar.addAction(self.menuImage_Alignment.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_button.setText(_translate("MainWindow", "Input Img"))
        self.quadDetect_button.setText(_translate("MainWindow", "Quad Detection"))
        self.surfaceF_button.setText(_translate("MainWindow", "Surface Flatten"))
        self.saveR_button.setText(_translate("MainWindow", "Save Result"))
        self.imgEnhance_button.setText(_translate("MainWindow", "Image Enhancement"))
        self.srcImg_label.setText(_translate("MainWindow", "Source Image"))
        self.result_label.setText(_translate("MainWindow", "Result"))
        self.srcImg_View.setText(_translate("MainWindow", "source image"))
        self.result_View.setText(_translate("MainWindow", "Result Image"))
        self.note_label.setText(_translate("MainWindow", "Please click \"Input Img\" button."))
        self.rotate_Button.setText(_translate("MainWindow", "Rotate Result"))
        self.menuImage_Alignment.setTitle(_translate("MainWindow", "Image Alignment"))
