# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'ImgEnhance.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(503, 369)
        self.Laplace_Button = QtWidgets.QPushButton(Dialog)
        self.Laplace_Button.setGeometry(QtCore.QRect(20, 260, 121, 31))
        self.Laplace_Button.setObjectName("Laplace_Button")
        self.Gamma_Button = QtWidgets.QPushButton(Dialog)
        self.Gamma_Button.setGeometry(QtCore.QRect(20, 209, 121, 31))
        self.Gamma_Button.setObjectName("Gamma_Button")
        self.Gamma_SpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.Gamma_SpinBox.setGeometry(QtCore.QRect(170, 210, 62, 31))
        self.Gamma_SpinBox.setMaximum(3.0)
        self.Gamma_SpinBox.setSingleStep(0.1)
        self.Gamma_SpinBox.setProperty("value", 1.0)
        self.Gamma_SpinBox.setObjectName("Gamma_SpinBox")
        self.Bright_Button = QtWidgets.QPushButton(Dialog)
        self.Bright_Button.setGeometry(QtCore.QRect(20, 10, 121, 31))
        self.Bright_Button.setObjectName("Bright_Button")
        self.Bright_SpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.Bright_SpinBox.setGeometry(QtCore.QRect(170, 11, 62, 31))
        self.Bright_SpinBox.setMaximum(3.0)
        self.Bright_SpinBox.setSingleStep(0.1)
        self.Bright_SpinBox.setProperty("value", 1.0)
        self.Bright_SpinBox.setObjectName("Bright_SpinBox")
        self.Color_Button = QtWidgets.QPushButton(Dialog)
        self.Color_Button.setGeometry(QtCore.QRect(20, 60, 121, 31))
        self.Color_Button.setObjectName("Color_Button")
        self.Color_SpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.Color_SpinBox.setGeometry(QtCore.QRect(170, 61, 62, 31))
        self.Color_SpinBox.setMaximum(3.0)
        self.Color_SpinBox.setSingleStep(0.1)
        self.Color_SpinBox.setProperty("value", 1.0)
        self.Color_SpinBox.setObjectName("Color_SpinBox")
        self.Contrast_Button = QtWidgets.QPushButton(Dialog)
        self.Contrast_Button.setGeometry(QtCore.QRect(20, 110, 121, 31))
        self.Contrast_Button.setObjectName("Contrast_Button")
        self.Contrast_SpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.Contrast_SpinBox.setGeometry(QtCore.QRect(170, 110, 61, 31))
        self.Contrast_SpinBox.setMaximum(3.0)
        self.Contrast_SpinBox.setSingleStep(0.1)
        self.Contrast_SpinBox.setProperty("value", 1.0)
        self.Contrast_SpinBox.setObjectName("Contrast_SpinBox")
        self.Sharp_Button = QtWidgets.QPushButton(Dialog)
        self.Sharp_Button.setGeometry(QtCore.QRect(20, 160, 121, 31))
        self.Sharp_Button.setObjectName("Sharp_Button")
        self.Sharp_SpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.Sharp_SpinBox.setGeometry(QtCore.QRect(170, 160, 61, 31))
        self.Sharp_SpinBox.setMaximum(10.0)
        self.Sharp_SpinBox.setSingleStep(0.3)
        self.Sharp_SpinBox.setProperty("value", 1.0)
        self.Sharp_SpinBox.setObjectName("Sharp_SpinBox")
        self.Reset_Button = QtWidgets.QPushButton(Dialog)
        self.Reset_Button.setGeometry(QtCore.QRect(170, 310, 101, 31))
        self.Reset_Button.setObjectName("Reset_Button")
        self.Save_Button = QtWidgets.QPushButton(Dialog)
        self.Save_Button.setGeometry(QtCore.QRect(290, 310, 101, 31))
        self.Save_Button.setObjectName("Save_Button")
        self.whitebg_Button = QtWidgets.QPushButton(Dialog)
        self.whitebg_Button.setGeometry(QtCore.QRect(300, 10, 171, 31))
        self.whitebg_Button.setObjectName("whitebg_Button")
        self.remove_redblue_Button = QtWidgets.QPushButton(Dialog)
        self.remove_redblue_Button.setGeometry(QtCore.QRect(300, 60, 171, 31))
        self.remove_redblue_Button.setObjectName("remove_redblue_Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Laplace_Button.setText(_translate("Dialog", "Run Laplace"))
        self.Gamma_Button.setText(_translate("Dialog", "Run Gamma"))
        self.Bright_Button.setText(_translate("Dialog", "Run Brightness"))
        self.Color_Button.setText(_translate("Dialog", "Run Color"))
        self.Contrast_Button.setText(_translate("Dialog", "Run Contrast"))
        self.Sharp_Button.setText(_translate("Dialog", "Run Sharpness"))
        self.Reset_Button.setText(_translate("Dialog", "Reset Image"))
        self.Save_Button.setText(_translate("Dialog", "Save Result"))
        self.whitebg_Button.setText(_translate("Dialog", "Black font & White bg"))
        self.remove_redblue_Button.setText(_translate("Dialog", "Remove red and blue"))
